"""Turn glossary/terms.jsonl (the single source) into the three things the site needs:

  includes/glossary.md              abbreviation definitions, auto-appended to every page (tap-to-define)
  docs/glossary.md                  the A-Z glossary page
  docs/javascripts/glossary-map.js  alias -> anchor map used by the tap popover

Each line of terms.jsonl: {"term": "...", "aliases": ["..."], "def": "...", "lesson": "week-01/day-1", "card": "core-calc"}
"""
from __future__ import annotations

import json

import lml_common as c


def variants(entry: dict) -> list[str]:
    """The term, its aliases, and Capitalized forms of each (abbr matching is case-sensitive)."""
    seen, out = set(), []
    for t in [entry["term"], *entry.get("aliases", [])]:
        for v in (t, t[:1].upper() + t[1:]):
            if v not in seen:
                seen.add(v)
                out.append(v)
    return out


def main() -> None:
    terms = sorted(c.load_terms(), key=lambda e: e["term"].lower())

    abbr = ["<!-- Generated by build_glossary.py from glossary/terms.jsonl. Do not edit. -->", ""]
    alias_map: dict[str, str] = {}
    for e in terms:
        definition = " ".join(e["def"].split())
        for v in variants(e):
            abbr.append(f"*[{v}]: {definition}")
            alias_map[v] = c.slug(e["term"])
    inc = c.ROOT / "includes"
    inc.mkdir(exist_ok=True)
    (inc / "glossary.md").write_text("\n".join(abbr) + "\n", encoding="utf-8", newline="\n")

    page = ["---", "title: Glossary", "---", "", "# Glossary", "",
            "Every dotted-underlined word in a lesson opens its definition when tapped. "
            "This page is the same list, A–Z, with the lesson that introduced each word.", ""]
    letter = ""
    for e in terms:
        first = e["term"][0].upper()
        if first != letter:
            letter = first
            page += [f"## {letter}", ""]
        page.append(f'<div class="gl-entry" id="{c.slug(e["term"])}" markdown>')
        page.append(f"**{e['term']}**" + (f" <small>(also: {', '.join(e['aliases'])})</small>" if e.get("aliases") else ""))
        page.append("")
        page.append(" ".join(e["def"].split()))
        page.append("")
        meta = []
        if e.get("lesson"):
            meta.append(f"first met in [{e['lesson']}]({e['lesson']}.md)")
        if e.get("card"):
            meta.append(f"canvas card `{e['card']}`")
        if meta:
            page.append("<small>" + " · ".join(meta) + "</small>")
        page += ["</div>", ""]
    (c.DOCS / "glossary.md").write_text("\n".join(page), encoding="utf-8", newline="\n")

    js_dir = c.DOCS / "javascripts"
    js_dir.mkdir(parents=True, exist_ok=True)
    (js_dir / "glossary-map.js").write_text(
        "// Generated by build_glossary.py. Do not edit.\nwindow.LEARNML_GLOSSARY = "
        + json.dumps(alias_map, ensure_ascii=False, sort_keys=True) + ";\n",
        encoding="utf-8", newline="\n")

    print(f"glossary: {len(terms)} terms, {len(alias_map)} tappable forms")


if __name__ == "__main__":
    main()
